const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.Anchor,
		C3.Behaviors.Fade,
		C3.Behaviors.Bullet,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.JavaScriptInEvents.Ejogo_Event3_Act2,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{imgFundo1: 0},
	{Solid: 0},
	{chão: 0},
	{estaAtacando: 0},
	{ataque: 0},
	{podeMorrer: 0},
	{invulneravel: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Flash: 0},
	{RestritoAoLayout: 0},
	{jogadora: 0},
	{Keyboard: 0},
	{Direcao: 0},
	{inimigo: 0},
	{sensor_Direcao_direita: 0},
	{sensor_Direcao_esquerda: 0},
	{vidas: 0},
	{Senóide: 0},
	{balaMagica: 0},
	{pirulitoMagico: 0},
	{chocolateMagico: 0},
	{Pontos: 0},
	{escadaChao: 0},
	{setaFim: 0},
	{fundoGameOver: 0},
	{Botão: 0},
	{Âncora: 0},
	{fundoFase2: 0},
	{fundoFase3: 0},
	{marChocolate: 0},
	{botaoIniciarJogo: 0},
	{arvore: 0},
	{espinho: 0},
	{Esmaecer: 0},
	{Projétil: 0},
	{fumaçaDano: 0},
	{Áudio: 0},
	{fundo_game_over: 0},
	{txtMorte: 0},
	{fundoIncioJogo: 0},
	{SpawnJogadora: 0},
	{NumerodaFase: 0},
	{MensagemMorte: 0},
	{passouFase: 0}
];

self.InstanceType = {
	imgFundo1: class extends self.ITiledBackgroundInstance {},
	chão: class extends self.ISpriteInstance {},
	jogadora: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	inimigo: class extends self.ISpriteInstance {},
	sensor_Direcao_direita: class extends self.ISpriteInstance {},
	sensor_Direcao_esquerda: class extends self.ISpriteInstance {},
	vidas: class extends self.ISpriteInstance {},
	balaMagica: class extends self.ISpriteInstance {},
	pirulitoMagico: class extends self.ISpriteInstance {},
	chocolateMagico: class extends self.ISpriteInstance {},
	Pontos: class extends self.ITextInstance {},
	escadaChao: class extends self.ISpriteInstance {},
	setaFim: class extends self.ISpriteInstance {},
	fundoGameOver: class extends self.ITiledBackgroundInstance {},
	Botão: class extends self.IButtonInstance {},
	fundoFase2: class extends self.ITiledBackgroundInstance {},
	fundoFase3: class extends self.ITiledBackgroundInstance {},
	marChocolate: class extends self.ISpriteInstance {},
	botaoIniciarJogo: class extends self.IButtonInstance {},
	arvore: class extends self.ISpriteInstance {},
	espinho: class extends self.ISpriteInstance {},
	fumaçaDano: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	fundo_game_over: class extends self.ISpriteInstance {},
	txtMorte: class extends self.ITextInstance {},
	fundoIncioJogo: class extends self.ISpriteInstance {},
	SpawnJogadora: class extends self.ISpriteInstance {}
}